### ISSUE TITLE
switch fileSystemPath in .dev from the default to...

### ISSUE THREAD

**Issue by buggedcom** [ten4design/ten4-framework#17]
```php
dirname(dirname(dirname(__FILE__))).'/public_html/',
```

and it will then work whereever it is being run on dev

**Comment by andygrn** [comment]
to what Ollie?? TO WHAT?!?

**Comment by buggedcom** [comment]
odd, github didn't like short script markup

**Comment by alexyoung91** [comment]
would using `realpath('../../public_html')` work instead of the three `dirname`s?

**Comment by andygrn** [comment]
`realpath(NULL).'/',` works for me

**Comment by buggedcom** [comment]
realpath behaves slightly differently depending on the OS used on the server. Whilst not a problem if always on Unix, if a client used windows for whatever shitty reason it would possibly become an issue in certain circumstances. Therefore dirname is more reliable.

**Comment by buggedcom** [comment]
alternatively use a variable from the $_SERVER superglobal to calculate the base path

**Comment by andygrn** [comment]
How bout `getcwd().'/'`? - `public_html` could change from server to server

**Comment by buggedcom** [comment]
should work, I think, however might have implications if for whatever reason you start using the command line and craft locally (- which is probably quite unlikely?)

**Comment by andygrn** [comment]
Realpath seems like the lesser of three evils, going with that for now
