### ISSUE TITLE
Gulp-ftp gives me deprecated notices

### ISSUE THREAD

**Issue by andygrn** [ten4design/ten4-framework#23]
Not that we use it, but deprecation notices must be CRUSHED

**Comment by lukepearce** [comment]
Could take a look at [dploy](http://leanmeanfightingmachine.github.io/dploy/). It's the FTP deployment thing I was showing you a while back.

**Comment by andygrn** [comment]
Potentially just get rid of this - does anyone use it?

**Comment by lukepearce** [comment]
Not yet.. but I think if a decent solution is found we would start using said solution.

**Comment by alexyoung91** [comment]
+1 on removing
