### ISSUE TITLE
External feeds async

### ISSUE THREAD

**Issue by andygrn** [ten4design/ten4-framework#29]
Done for zab - asynchronously loads tweets, instagrams etc so the page doesn't break when the feeds do.

**Comment by lukepearce** [comment]
oooooo fancy pants

On 7 April 2015 at 11:48, Andy Green <notifications@github.com> wrote:

> Done for zab - asynchronously loads tweets, instagrams etc so the page
> doesn't break when the feeds do.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ten4design/ten4-framework/issues/29>.
>



-- 
*Luke Pearce*
Developer

020 7613 0590 / ten4design.co.uk / @ten4design
