### ISSUE TITLE
Gulp watch task needs to be restarted to watch new files

### ISSUE THREAD

**Issue by lukepearce** [ten4design/ten4-framework#3]
Refactor watch task to automatically watch newly created files - I've found this only happens for scss files currently.

**Comment by andygrn** [comment]
Happens to templates too for me.

**Comment by alexyoung91** [comment]
This isn't a bug, gulp.watch just doesn't watch for new files, more of an enhancement i'd say chaps. We could look into gulp-watch? http://stackoverflow.com/questions/22391527/gulps-gulp-watch-not-triggered-for-new-or-deleted-files
