### ISSUE TITLE
Create Yeoman Generator for setting up a new project

### ISSUE THREAD

**Issue by lukepearce** [ten4design/ten4-framework#34]
Let's make it as simple as possible to use this framework as it's getting more and more complicated with each feature we add.

Look into rolling the installer.sh file into a Yeoman generator for better question asking features.

![image](https://cloud.githubusercontent.com/assets/1732601/7295047/7ab551b8-e9aa-11e4-9928-9a15c3fe5579.png)

http://yeoman.io/authoring/

**Comment by andygrn** [comment]
Ten4 installer baby 😎
