### ISSUE TITLE
Issue with font, possibly framework related?

### ISSUE THREAD

**Issue by alexyoung91** [ten4design/ten4-framework#42]
![screen shot 2015-05-07 at 14 43 08](https://cloud.githubusercontent.com/assets/1319456/7516526/edaf6dde-f4c7-11e4-88cf-d746a1de7f3f.png)

**Comment by lukepearce** [comment]
![screen shot 2015-05-07 at 15 18 52](https://cloud.githubusercontent.com/assets/1732601/7517375/963fe59c-f4cc-11e4-8db9-6f1f68c08a6c.png)

**Comment by lukepearce** [comment]
It's not a very consistent error which isn't helping to debug. It also sorts itself out when the browser re-draws itself...

**Comment by andygrn** [comment]
if it’s only recently started happening and doesn’t always appear, it’s probably a browser bug.

**Comment by lukepearce** [comment]
Always trying to shift the blame you are Andy...

**Comment by alexyoung91** [comment]
obvs andy's fault

**Comment by andygrn** [comment]
What version y'all on?
Me 42.0.2311.135 and I haven't seen this happen yet.

**Comment by alexyoung91** [comment]
42.0.2311.135 (64-bit)

**Comment by andygrn** [comment]
Confirmed happening on old framework too (http://www.sheppardrobson.com/).
