### ISSUE TITLE
consider adding a vagrant file to the repo and setup the framework for ScotchBox

### ISSUE THREAD

**Issue by buggedcom** [ten4design/ten4-framework#45]
so that it eases development across multiple machines.

https://box.scotch.io/

**Comment by andygrn** [comment]
We don't use Vagrant, and our server specs can change per-project. Something like this is better kept by you, rather than here.

**Comment by buggedcom** [comment]
that's half the point about using a vagrant file. it's ridiculous how easy it is to change server specs using a vagrant file and bootstrap.sh file. when you get a free moment, look into vagrant.
