### ISSUE TITLE
remove all compiled assets before copying/building

### ISSUE THREAD

**Issue by lukepearce** [ten4design/ten4-framework#46]
Having a problem with files/folders that I've put in `raw/fonts` being copied to `public_html/fonts` and when they are removed from `raw/fonts` they're still in `public_html/fonts`.

Pretty sure we could fix this by removing the folder before re-compiling/moving.

**Comment by lukepearce** [comment]
Do this @lukepearce

**Comment by andygrn** [comment]
Fixed in v3 with `purge` command
