### ISSUE TITLE
Ignore user uploads, find new backup process

### ISSUE THREAD

**Issue by andygrn** [ten4design/ten4-framework#50]
This separates site from content, which is a good idea, but we will need another backup process for uploads if it goes ahead. Zip file, submodule, etc.

**Comment by alexyoung91** [comment]
If we compress and upload database + uploads folder together when we do a content backup, this will be enough. Uploads remains ignored, database backups are ignored in the repo aswell. Thoughtsss?

**Comment by andygrn** [comment]
Process: Zip the database SQL with the uploaded files and stick it on the matrix. Bob is your uncle.
