### ISSUE TITLE
Bad SCSS shouldn't crash watch task

### ISSUE THREAD

**Issue by andygrn** [ten4design/ten4-framework#54]
It's flippin' annoying

**Comment by lukepearce** [comment]
Who's writing the bad SCSS though mr.green?

**Comment by lukepearce** [comment]
(On a serious note, I thought this was already the case?)

**Comment by alexyoung91** [comment]
plus one, try catch job?

**Comment by lukepearce** [comment]
This is already in our gulpfile..
```
.pipe( sass( {
   errLogToConsole:true
} ) )
```
http://stackoverflow.com/questions/21080433/gulp-sass-watch-stops-when-invalid-property-name

**Comment by andygrn** [comment]
DONT WORK THO M8

**Comment by andygrn** [comment]
Dunno if latest gulp-sass ignores it, this is a fairly new npm install

**Comment by lukepearce** [comment]
![image](https://cloud.githubusercontent.com/assets/1732601/7863401/182b1ec2-0554-11e5-9684-59e467457597.png)

**Comment by lukepearce** [comment]
![](http://digiday.com/wp-content/uploads/2013/05/shrug.gif)

**Comment by alexyoung91** [comment]
![screen shot 2015-05-28 at 16 10 59](https://cloud.githubusercontent.com/assets/1319456/7863407/299b1090-0554-11e5-8810-3024e27af34f.png)
