### ISSUE TITLE
Rename $type-base-size to something shorter

### ISSUE THREAD

**Issue by andygrn** [ten4design/ten4-framework#56]
I use it on every other line, so what about calling it $tb or something to de-clutter a bit?

**Comment by andygrn** [comment]
Or something less disease-y

**Comment by lukepearce** [comment]
Might be a good idea to abstract it away from "type" as we use it for all sorts of spacing etc. `$base-unit` or `$b-unit` or `$bu`.. we can also re-name per project too... just add `$chosen-name: $type-base-size` to your variables file.

**Comment by andygrn** [comment]
Yeah I like the base idea, this would only be for new projects going forwards, so I don't think aliases are necessary.

Changing this means we can do `$type-base-size = $base` and use `font-size: $type-base-size;` on the body, so we can increase body text size without breaking everything else (something I have wished I had before).

**Comment by lukepearce** [comment]
I quite like the fact that the `$type-base-size` is coupled with my spacing units for things. It means if I increase body font-size it increases all the spacing accordingly. Becomes especially helpful for margins on headings if they're not using an `em` value.

In my old framework I had the equivalent of `$type-base-size` and `$base-line-height` - I then used `$base-line-height` as my spacing unit so they could change independently. It was more in line with how type and grids are set in print design.

**Comment by andygrn** [comment]
You can still do that if you like - I prefer not to in most cases, but this way we have the option. If something should rely on base text size, multiply it by that, otherwise by the base unit.
