### ISSUE TITLE
Switch from css lint to scss lint

### ISSUE THREAD

**Issue by lukepearce** [ten4design/ten4-framework#58]
Opening up the compiled CSS file to find the line it's complaining about and then having to find where that style is in our scss files is looooooooooong.

Just switched to [SCSS lint](https://github.com/juanfran/gulp-scss-lint) on flowers and gives me which sass file the error is in and the line number. Will need to configure to our preferred rules.

Happy to change this and submit a PR if you're happy to switch?

**Comment by andygrn** [comment]
Linting SCSS isn't the same as linting CSS (and it's not that hard to ctrl-F a selector if it's not minified). We can do both, but scss-lint introduces a ruby dependency which we could do without. No javascript version?

**Comment by lukepearce** [comment]
No non ruby version. I did think about the difference between linting SCSS before and after compilation.. but in my mind I can't see how you could get errors in your CSS if the SCSS has been linted to our specifications? 

It's not finding the selector in the CSS that's hard, it's then finding which SCSS file it's in.. I've added sourcemaps to flowers which helps me find selectors when I'm looking in the web inspector - and theres a gulp task that combines these with CSS lint but it's not as widely used as SCSS lint (looking at the npm download numbers.)

**Comment by lukepearce** [comment]
Going through the config for SCSS lint I think it might be an excellent idea to lint pre-compiled code!

**Comment by lukepearce** [comment]
for reference:
https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md

**Comment by andygrn** [comment]
Fixed in v3
