### ISSUE TITLE
cache-breaking

### ISSUE THREAD

**Issue by jstewartdesign** [ten4design/ten4-framework#60]
However many times I say it, clients still complain when they can't see changes as they haven't cleared their cache. This is for assets (CSS, Images, SVGs, JS etc) not so much for pages. Which makes me feel some regular website visitors must experience the same thing?

Is there a way to include some cache-breaking/busting mechanism into the asset build process? Either by creating random file names for inclusion into templates, or some sort of versioning using query strings?

Would be very helpful knowing I'm sending a link to a client and it'll look the same to them as it does to me (minus any browser funkyness).

**Comment by andygrn** [comment]
We discussed having an auto-query-string asset path thing, enabled when in dev mode. Wouldn't be too difficult.

**Comment by lukepearce** [comment]
This would be ok before launch but we rarely make updates to a staging server to show to clients once a site has launched. Dev mode or not, I think cache busting assets are a good thing for all environments/modes. Can you see any complications?

**Comment by andygrn** [comment]
How do you propose to signal an asset needs cache breaking?

**Comment by lukepearce** [comment]
With our new and enhanced build process of course...

Something along the lines of gulp writing a unique string to the filename when it processes it and then writing the new filename to a template.

Modern web frameworks handle it just fine so can see about borrowing their method.

**Comment by lukepearce** [comment]
ignore that.. im being dumb. you don't have to change filenames. You just append query strings

https://www.npmjs.com/package/gulp-cache-bust

**Comment by lukepearce** [comment]
We've developed a Craft plugin to take care of this now. More info - https://github.com/ten4design/cmdr
