### ISSUE TITLE
Unitless unit

### ISSUE THREAD

**Issue by lukepearce** [ten4design/ten4-framework#64]
Im adding font sizes to a new project and would like them to be relative to the base unit.

I'm taking explicit values from a PSD in pixels.

```
.h2 {
  font-size: $unit * ( EXPLICIT_PIXEL_VALUE / $unit );
}
```

This part of the above needs to be unitless value `( EXPLICIT_PIXEL_VALUE / $unit )`

Whats the solution?

**Comment by lukepearce** [comment]
Also, should our font-size declarations be fixed pixel values of as a relative unit to the body's font size? This would allow us to scale the site easily by reducing/increasing the body's font size per breakpoint?

**Comment by andygrn** [comment]
Regarding point 1, I'm not sure what the question is.

Regarding point 2, that's what the old framework did, but I've found in practice it's nicer to have control over individual sizes (`.alpha`, `.beta`, etc.) than changing the whole site every breakpoint. But presumably if you change the value of `$unit` to an `em` value you will get this for free?
