### ISSUE TITLE
watch task still requires restart of gulp after adding new files

### ISSUE THREAD

**Issue by lukepearce** [ten4design/ten4-framework#65]

**Comment by andygrn** [comment]
Can't reproduce this, what type of file are you adding?

**Comment by lukepearce** [comment]
created a new folder under `sass` and added `.scss` files.

**Comment by lukepearce** [comment]
Sorry, it triggers the css task but doesn't trigger live reload.

**Comment by lukepearce** [comment]
Third time lucky: I don't have to restart gulp but I do have to refresh the browser.

**Comment by lukepearce** [comment]
Not sure what was going on but seems to be ok now..
